name: deploy-to-k8s

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Deploy to Namespace
        uses: Agile-Software-Engineering-25/deploy-to-k8s@v1.0.1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          namespace: ${{ vars.K8S_NAMESPACE }}
